### ISSUE TITLE
Excellent work

### ISSUE THREAD

**Issue by knowhatamine** [WebReflection/coincident#50]
I don't know if there's a better place to say this, but I just wanted to give you my thanks and let you know how brilliant this project is. Kudos!!

**Comment by WebReflection** [comment]
Thank you 🙏

It's great from time to time to be recognized and I do appreciate your comment. This project packs tons of modern features most developers usually either ignore or don't even know existed and I think I indeed nailed some part previously "*unthinkable*" or nowhere out there as *JS* offer.

I can glue things around to enable Polyscript, PyScript, IoT related projects, GitHub pages with also SQLite (WASM) stored as IndexedDB on changes, the stuff I am doing with *coincident* is huge but if the community would give it a try or spread the word I think even more "*unthinkable*" ideas might flourish and I can't wait to see these live and working well 🥳
